[profile.ci]
src = 'src'                                                   # the source directory
out = 'out'                                                   # the output directory (for artifacts)
libs = ['lib']                                                # a list of library directories
remappings = [
  "solmate/=lib/solmate/src/",
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/=lib/openzeppelin-contracts/"
]
ffi = false
fuzz_runs = 256
optimizer = true
optimizer_runs = 1000000

verbosity = 1

# Extreme Fuzzing CI Profile :P
[ci]
fuzz_runs = 100_000
verbosity = 4